#line 2 "start.c"

#line 4 "start.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[207] =
    {   0,
        0,    0,    0,    0,   68,   68,   63,   63,    0,    0,
       80,   79,    1,   39,   58,   78,   22,   34,   79,   40,
       41,   20,   18,   46,   19,   78,   21,   48,   47,   25,
       31,   27,   71,   44,   45,   36,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   42,   35,   43,   79,
       60,   79,   79,   68,   67,   69,   63,   64,   63,   70,
       30,   32,    0,    0,   50,   52,    0,   23,   24,   49,
       61,   65,   77,   75,   48,   77,   37,   26,   29,   28,
       38,   71,   71,   71,   71,   71,   71,    6,   71,   71,
       71,    2,   71,   71,   71,   71,   71,   33,    0,   59,

       60,   59,    0,    0,   59,   60,    0,    0,   68,   66,
       63,   63,   62,    0,   51,   57,    0,    0,    0,   53,
        0,   76,   76,   72,   49,   76,   77,   76,   71,   71,
       71,   71,   71,   71,   71,   71,    4,    8,   71,   71,
       71,   71,   54,    0,   55,   57,    0,    0,   49,   74,
       76,   74,   76,   76,   72,   72,   77,   76,   76,   75,
       76,   71,   15,    9,   71,   71,   71,    3,   71,   71,
       71,   12,   71,   56,   74,   76,   74,   76,   76,   76,
       72,   72,   77,   49,   74,   75,    7,   71,   71,   71,
       10,   71,   71,    5,   74,   73,   71,   71,   11,   13,

       14,   73,   71,   16,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    3,    4,
        2,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    9,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   32,    9,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   39,   42,   43,   39,   44,
       45,   39,   39,   46,   47,   48,   49,   50,   51,   39,
       39,   39,   52,   53,   54,    9,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    3,    4,    2,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    7,    1,    1,    1,
        8,    4,    1,    1,    1,    8,    8,    1,    6,    1,
        1,    9,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[221] =
    {   0,
        0,    0,   47,   91,  142,    0,  196,    0,  248,    0,
      645,  646,  646,  620,  646,  646,  646,  632,  298,  646,
      646,  646,  626,  646,  623,  619,   41,   38,  646,   39,
      615,   42,    0,  646,  646,  646,  592,   67,   23,  594,
       26,   20,  599,  584,  589,  593,  646,  579,  646,   66,
      627,   69,  327,    0,  646,  626,  614,  646,   86,  646,
      646,  646,   98,   99,    0,  616,  378,  646,  646,   51,
      646,  646,    0,  396,   94,   98,  646,  646,  646,  646,
      646,    0,  590,  564,  544,  531,  524,  511,  512,  513,
      508,    0,  505,  504,  510,  492,  491,  646,  523,  502,

      646,  646,  505,   71,  100,  504,  101,    0,    0,  646,
      492,  102,  646,  249,  646,  646,  492,  252,  253,  490,
      250,  426,  251,  430,  285,  455,  480,  239,  467,  462,
      452,  449,  463,  461,  457,  460,    0,    0,  443,  443,
      448,  436,  646,  255,  463,  443,  438,  425,  404,  459,
      286,  290,  294,  376,  295,  299,  303,  484,  304,  364,
      368,  378,    0,    0,  373,  364,  366,    0,  357,  342,
      349,    0,  289,  310,  372,  377,  385,  389,  400,  418,
      419,  422,  287,  423,  435,  447,    0,  236,  236,  239,
        0,  229,  222,    0,  448,  451,  206,   75,    0,    0,

        0,  464,   81,    0,    0,  646,  511,  520,  529,  531,
      540,  548,  555,  563,  572,  581,  590,  599,  608,  617
    } ;

static const flex_int16_t yy_def[221] =
    {   0,
      206,    1,  207,  207,  206,    5,  206,    7,    7,    9,
      206,  206,  206,  206,  206,  206,  206,  206,  208,  206,
      206,  206,  206,  206,  206,  206,  206,  209,  206,  206,
      206,  206,  210,  206,  206,  206,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  206,  206,  206,  211,
      206,  211,  206,  212,  206,  206,  213,  206,  213,  206,
      206,  206,  214,  214,  215,  215,  216,  206,  206,  206,
      206,  206,  209,  217,  209,  209,  206,  206,  206,  206,
      206,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  206,  211,  211,

      206,  206,   53,  211,  211,  206,  211,   53,  212,  206,
      213,  213,  206,  214,  206,  206,  215,  218,  218,  219,
      206,  217,  220,  217,  209,  217,  209,  209,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  206,  218,  219,  219,  219,  206,  206,  217,
      209,  220,  206,  220,  209,  209,  209,  217,  209,  209,
      209,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  219,  209,  209,  206,  206,  220,  206,
      209,  209,  209,  209,  209,  209,  210,  210,  210,  210,
      210,  210,  210,  210,  206,  209,  210,  210,  210,  210,

      210,  209,  210,  210,  210,    0,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206
    } ;

static const flex_int16_t yy_nxt[701] =
    {   0,
       12,   12,   12,   13,   12,   12,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   33,   34,   12,   35,
       36,   33,   33,   37,   38,   39,   40,   41,   33,   33,
       42,   33,   33,   33,   33,   43,   44,   33,   33,   45,
       46,   47,   48,   49,   51,   71,   74,   92,   75,   87,
       72,   77,   78,   93,   76,   80,   81,   88,   90,  100,
       91,   70,  103,  101,  100,   52,  101,  121,  101,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   51,   84,

      112,  115,  115,  100,  103,  113,   85,  101,  101,  116,
      206,   86,   74,  127,   75,  127,  112,  205,  128,   52,
       76,  113,  204,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   12,   12,   54,   55,   12,   54,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   54,   12,
       12,   12,   54,   12,   12,   12,   12,   54,   54,   12,
       56,   12,   12,   12,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   12,   12,   12,   12,   12,   57,   58,

       12,   57,   12,   12,   12,   12,   12,   12,   12,   12,
       59,   12,   12,   12,   12,   12,   57,   12,   12,   12,
       12,   57,   57,   12,   57,   12,   12,   12,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   12,   12,   12,
       12,   60,  115,   12,  203,  115,  115,  160,  115,  161,
      143,  201,   12,  145,  146,  148,  174,  148,   12,  152,
      149,  153,  200,   12,   12,  199,   12,  154,  198,  197,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   64,

       64,   65,   64,  156,  176,  125,  151,  184,  152,   66,
      177,  157,  178,  181,  153,  155,  154,  156,  183,  182,
      183,  174,  185,  184,  159,  194,   67,  104,  104,  104,
      105,  104,  104,  104,  106,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  107,  104,  104,  104,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  104,  104,
      104,  115,  160,  193,  186,  119,  160,  192,  161,  120,
      185,  179,  175,  179,  152,  176,  180,  151,  123,  123,

      123,  123,  154,  195,  191,  177,  119,  178,  190,  153,
      119,  119,  189,  188,  124,  119,  125,  123,  152,  187,
      180,  119,  126,  119,  149,  119,  154,  119,  123,  123,
      123,  123,  123,  123,  123,  123,  195,  181,  180,  155,
      156,  196,  182,  184,  150,  149,  151,  123,  124,  174,
      155,  123,  126,  185,  174,  175,  126,  123,  123,  123,
      123,  123,  123,  123,  123,  160,  195,  186,  177,  196,
      158,  202,  158,  150,  174,  159,  123,  150,  173,  175,
      123,  126,  196,  172,  202,  126,  123,  123,  123,  123,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,

      128,  146,  150,  143,  159,  123,  112,  102,  104,  101,
      126,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   73,
      101,  142,  141,   73,   73,   73,   73,   73,   82,   82,
       99,   99,   99,   99,   99,   99,   99,   99,   99,  109,
      140,  139,  138,  137,  109,  109,  111,  136,  135,  134,
      111,  133,  111,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  117,  117,  132,  117,  131,  117,  117,  117,
      117,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  147,  147,
      130,  147,  147,  147,  147,  147,  147,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  129,  116,  112,  110,
      102,   98,   97,   96,   95,   94,   89,   83,   79,   70,
       69,   68,   62,   61,  206,   11,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206

    } ;

static const flex_int16_t yy_chk[701] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,   27,   28,   42,   28,   39,
       27,   30,   30,   42,   28,   32,   32,   39,   41,   50,
       41,   70,   52,   50,  104,    3,   52,   70,  104,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    4,   38,

       59,   63,   64,  105,  107,   59,   38,  105,  107,   63,
       64,   38,   75,   76,   75,   76,  112,  203,   76,    4,
       75,  112,  198,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        9,    9,  114,    9,  197,  118,  119,  128,  144,  128,
      114,  193,    9,  118,  119,  121,  144,  121,    9,  123,
      121,  123,  192,    9,    9,  190,    9,  123,  189,  188,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   19,

       19,   19,   19,  125,  151,  125,  151,  183,  152,   19,
      152,  125,  153,  155,  153,  155,  152,  156,  157,  156,
      157,  174,  159,  157,  159,  173,   19,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   67,  160,  171,  160,   67,  161,  170,  161,   67,
      175,  154,  175,  154,  154,  176,  154,  176,   74,   74,

       74,   74,  154,  177,  169,  177,   67,  178,  167,  178,
       67,   67,  166,  165,   74,   67,   74,   74,  179,  162,
      179,   67,   74,   67,  149,   67,  179,   67,  122,  122,
      122,  122,  124,  124,  124,  124,  180,  181,  180,  181,
      182,  184,  182,  184,  122,  148,  122,  122,  124,  147,
      124,  124,  122,  185,  146,  185,  124,  126,  126,  126,
      126,  150,  150,  150,  150,  186,  195,  186,  195,  196,
      126,  196,  126,  126,  145,  126,  126,  150,  142,  150,
      150,  126,  202,  141,  202,  150,  158,  158,  158,  158,
      140,  139,  136,  135,  134,  133,  132,  131,  130,  129,

      127,  120,  158,  117,  158,  158,  111,  106,  103,  100,
      158,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  209,
       99,   97,   96,  209,  209,  209,  209,  209,  210,  210,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  212,
       95,   94,   93,   91,  212,  212,  213,   90,   89,   88,
      213,   87,  213,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  215,  215,   86,  215,   85,  215,  215,  215,
      215,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  219,  219,
       84,  219,  219,  219,  219,  219,  219,  220,  220,  220,
      220,  220,  220,  220,  220,  220,   83,   66,   57,   56,
       51,   48,   46,   45,   44,   43,   40,   37,   31,   26,
       25,   23,   18,   14,   11,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "start.l"




#line 9 "start.l"
#include <bits/stdc++.h>
#include<fstream>
using namespace std;
#define ll long long

int line_count=1;
int err_count = 0;

FILE *logout;
FILE *tokenout;
class SymbolInfo
{
    string name;
    string type;
public:

    SymbolInfo* lc;
    SymbolInfo* rc;

    SymbolInfo()
    {
        lc = NULL;
        rc = NULL;
    }
    SymbolInfo(string key, string val)
    {
        lc = NULL;
        rc = NULL;
        name = key;
        type = val;
    }
    ~SymbolInfo()
    {

    }
    string getName()
    {
        return name;
    }
    string getType()
    {
        return type;
    }
    void setName(string s)
    {
        name = s;
    }
    void setType(string s)
    {
        type = s;
    }
};


class ScopeTable
{
public:

    SymbolInfo** p;
    ScopeTable* parent_scope;
    int num_buckets;
    int unique_number;

    ScopeTable(int total, int number, ScopeTable* parent_pointer = NULL)
    {
        cout<<"\tScopeTable# "<<number<<" created"<<endl;
        num_buckets = total;
        unique_number = number;
        p = new SymbolInfo*[num_buckets];
        for(int i=0;i<num_buckets;i++)
        {
            p[i]=NULL;
        }
        parent_scope = parent_pointer;
    }
    ~ScopeTable()
    {
        cout<<"\t"<<"ScopeTable# "<<unique_number<<" removed"<<endl;
        for(int i=0;i<num_buckets;i++)
        {
            SymbolInfo* now=p[i];
            while(now!=NULL)
            {
                SymbolInfo* temp=now;
                now=now->rc;
                delete temp;
            }
        }
        delete p;
    }
    ll SDBMHash(string str)
    {
        ll hashval = 0;
        ll i = 0;
        ll len = str.length();

        for (i = 0; i < len; i++)
        {
            hashval = (str[i]) + (hashval << 6) + (hashval << 16) - hashval;
            hashval =hashval % num_buckets;
        }

        return hashval;
    }
    SymbolInfo* searchHelp(string k)
    {
        ll index = SDBMHash(k);
        index = index % num_buckets;
        SymbolInfo* temp = p[index];
        while(temp!=NULL)
        {
            if(temp->getName()==k)
                break;
            temp=temp->rc;
        }
        return temp;
    }
    void deleteHash(string k)
    {
        ll index = SDBMHash(k);
        index = index % num_buckets;
        SymbolInfo* found = searchHelp(k);
        if(found==NULL)
        {
            return;
        }
        else

        {
            if(found->lc!=NULL)
            {
                found->lc->rc=found->rc;
            }
            if(found->rc!=NULL)
            {
                found->rc->lc=found->lc;
            }
            if(found->lc==NULL)
            {
                p[index]=found->rc;
            }

            delete found;
        }
    }

    SymbolInfo* searchHash(string k)
    {
        SymbolInfo* found=searchHelp(k);
        return found;
    }

    bool insertHash(string k, string value)
    {
        ll index = SDBMHash(k);
        index = index % num_buckets;

        SymbolInfo* obj;

        SymbolInfo* found=searchHelp(k);
        if(found!=NULL)
        {
            return false;
        }

        if(p[index]==NULL) // first position to insert
        {
            obj=new SymbolInfo(k,value);
            p[index]=obj;
        }
        else
        {
            SymbolInfo* now = p[index];
            while(now->rc!=NULL)
            {
                now=now->rc;
            }
            obj=new SymbolInfo(k,value);
            now->rc=obj;
            obj->lc=now;
        }
        return true;
    }

    int getIndexInfoFirst(string key, string val="")
    {
        ll index = SDBMHash(key);
        index = index % num_buckets;

        SymbolInfo* now = p[index];
        bool ok=false;

        while(now!=NULL)
        {
            if(now->getName()==key)
            {
                ok=true; break;
            }
            now=now->rc;
        }
        if(ok){
            return index;
        }
        else
        {
            return -1;
        }
    }


    int getIndexInfoSecond(string key, string val="")
    {
        ll index = SDBMHash(key);
        index = index % num_buckets;

        SymbolInfo* now = p[index];
        int where=1;
        bool ok=false;

        while(now!=NULL)
        {
            if(now->getName()==key)
            {
                ok=true; break;
            }
            now=now->rc;
            where++;
        }
        if(ok){
            return where;
        }
        else
        {
            return -1;
        }
    }




    void print()
    {	
	fprintf(logout,"\tScopeTable# %d\n",unique_number);	
        for(int i=0;i<num_buckets;i++)
        {
            SymbolInfo* now=p[i];
	   if(now==NULL) continue; int i2=i+1;
	  fprintf(logout,"\t%d--> ",i2);
            while(now!=NULL)
            {	
		string nowName = now->getName();
		string nowType = "ID";
		char nowName2[500], nowType2[500];
		int i;
		for(i=0;i<nowName.size();i++)
		{ 
			nowName2[i]=nowName[i];
		}
		nowName2[i]='\0';
		for(i=0;i<nowType.size();i++)
		{ 
			nowType2[i]=nowType[i];
		}
		nowType2[i]='\0';
		
		fprintf(logout,"<%s,%s> ",nowName2,nowType2);
		cout<<nowName<<" "<<nowType<<endl;
                now=now->rc;
            }
		fprintf(logout,"\n");
            
        }
    }
};
class SymbolTable
{
    ScopeTable* curr_scope_table;
    int curr_size;
public:
    int getCurrSize()
    {
        return curr_scope_table->unique_number;
    }
    SymbolTable()
    {
        curr_scope_table = NULL;
        curr_size = 0;
    }
    void clearTable()
    {
        ScopeTable* now = curr_scope_table;
        while(now!=NULL)
        {
            ScopeTable* nextPointer = now->parent_scope;
            delete now;
            now = nextPointer;
        }
        curr_scope_table=NULL;
    }
    ~SymbolTable()
    {
        clearTable();
    }
    void EnterScope(int total)
    {
        curr_size++;
        ScopeTable* temp = new ScopeTable(total, curr_size, curr_scope_table);
        curr_scope_table = temp;
    }
    bool ExitScope()
    {
        if(curr_scope_table->unique_number == 1)
        {
            return false;
        }
        ScopeTable* temp = curr_scope_table->parent_scope;
        delete curr_scope_table;
        curr_scope_table = temp;
        return true;
    }
    bool Insert(string key, string val)
    {
        bool result = curr_scope_table->insertHash(key, val);
        return result;
    }
    bool Delete(string key)
    {
        SymbolInfo* found=curr_scope_table->searchHelp(key);
        if(found==NULL)
        {
            return false;// nothing to delete
        }
        curr_scope_table->deleteHash(key);
        return true;
    }
    int LookUp(string key)
    {
        ScopeTable* now = curr_scope_table;
        SymbolInfo* result=NULL;
        while(now!=NULL)
        {
            result = now->searchHash(key);
            if(result!=NULL)
            {
                break; // we got here
            }
            now = now->parent_scope;
        }
        if(result!=NULL)
        {
            return now->unique_number;
        }
        else
        {
            return -1;
        }
    }
    void PrintCurrentScopeTable()
    {
        curr_scope_table->print();
    }
    void PrintAllScopeTable()
    {
        ScopeTable* now = curr_scope_table;
        while(now!=NULL)
        {
            now->print();
            now=now->parent_scope;
        }
    }
    int getIndexInfoFirst(string key, string val="")
    {
        ScopeTable* now = curr_scope_table;
        int p=-1;
        while(now!=NULL)
        {
            p=now->getIndexInfoFirst(key);
            if(p!=-1)
            {
                break;
            }
            now=now->parent_scope;
        }
        return p;
    }
    int getIndexInfoSecond(string key, string val="")
    {
        int p=-1;
        ScopeTable* now = curr_scope_table;
        while(now!=NULL)
        {
            p=now->getIndexInfoSecond(key);
            if(p!=-1)
            {
                break;
            }
            now=now->parent_scope;
        }
        return p;
    }
};

SymbolTable symbolTable;
#line 1078 "start.c"
#line 1079 "start.c"

#define INITIAL 0
#define STRINGSTART 1
#define SINGLECOMMENTSTART 2
#define MULTIPLECOMMENTSTART 3
#define SINGLECOMMENTSTART2 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 420 "start.l"


#line 1303 "start.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 207 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 646 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 422 "start.l"
{	line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 424 "start.l"
{
			fprintf(tokenout,"<IF, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <IF> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 428 "start.l"
{
			fprintf(tokenout,"<ELSE, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <ELSE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 432 "start.l"
{
			fprintf(tokenout,"<FOR, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <FOR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 436 "start.l"
{
			fprintf(tokenout,"<WHILE, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <WHILE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 440 "start.l"
{
			fprintf(tokenout,"<DO, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <DO> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 444 "start.l"
{
			fprintf(tokenout,"<BREAK, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <BREAK> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 448 "start.l"
{
			fprintf(tokenout,"<INT, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <INT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 452 "start.l"
{
			fprintf(tokenout,"<CHAR, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <CHAR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 456 "start.l"
{
			fprintf(tokenout,"<FLOAT, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <FLOAT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 460 "start.l"
{
			fprintf(tokenout,"<DOUBLE, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <DOUBLE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 464 "start.l"
{
			fprintf(tokenout,"<VOID, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <VOID> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 468 "start.l"
{
			fprintf(tokenout,"<RETURN, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <RETURN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 472 "start.l"
{
			fprintf(tokenout,"<SWITCH, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <SWITCH> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 476 "start.l"
{
			fprintf(tokenout,"<CASE, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <CASE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 480 "start.l"
{
			fprintf(tokenout,"<DEFAULT, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <DEFAULT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 484 "start.l"
{
			fprintf(tokenout,"<CONTINUE, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <CONTINUE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 18:
#line 489 "start.l"
case 19:
YY_RULE_SETUP
#line 490 "start.l"
{
			fprintf(tokenout,"<ADDOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <ADDOP> Lexeme %s found\n",line_count,yytext);
			//insert in symbol table and print symbol table content(only non empty buckets)
			// There is a '|' in "+"'s rule, this means match execute the action for following rule
		}
	YY_BREAK
case 20:
#line 497 "start.l"
case 21:
#line 498 "start.l"
case 22:
YY_RULE_SETUP
#line 499 "start.l"
{
			fprintf(tokenout,"<MULOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <MULOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 23:
#line 504 "start.l"
case 24:
YY_RULE_SETUP
#line 505 "start.l"
{
			fprintf(tokenout,"<INCOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <INCOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 25:
#line 510 "start.l"
case 26:
#line 511 "start.l"
case 27:
#line 512 "start.l"
case 28:
#line 513 "start.l"
case 29:
#line 514 "start.l"
case 30:
YY_RULE_SETUP
#line 514 "start.l"
{
			fprintf(tokenout,"<RELOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RELOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 518 "start.l"
{
			fprintf(tokenout,"<ASSIGNOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <ASSIGNOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 32:
#line 523 "start.l"
case 33:
YY_RULE_SETUP
#line 523 "start.l"
{
			fprintf(tokenout,"<LOGICLOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LOGICLOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 34:
#line 528 "start.l"
case 35:
#line 529 "start.l"
case 36:
#line 530 "start.l"
case 37:
#line 531 "start.l"
case 38:
YY_RULE_SETUP
#line 531 "start.l"
{
			fprintf(tokenout,"<BITOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <BITOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 535 "start.l"
{
			fprintf(tokenout,"<NOT, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <NOT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 539 "start.l"
{
			fprintf(tokenout,"<LPAREN, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LPAREN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 543 "start.l"
{
			fprintf(tokenout,"<RPAREN, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RPAREN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 547 "start.l"
{
			fprintf(tokenout,"<LCURL, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LCURL> Lexeme %s found\n",line_count,yytext);symbolTable.EnterScope(10);
		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 551 "start.l"
{
			fprintf(tokenout,"<RCURL, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RCURL> Lexeme %s found\n",line_count,yytext);symbolTable.ExitScope();
		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 555 "start.l"
{
			fprintf(tokenout,"<LSQUARE, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LSQUARE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 559 "start.l"
{
			fprintf(tokenout,"<RSQUARE, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RSQUARE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 563 "start.l"
{
			fprintf(tokenout,"<COMMA, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <COMMA> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 567 "start.l"
{
			fprintf(tokenout,"<SEMICOLON, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <SEMICOLON> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 571 "start.l"
{
			fprintf(tokenout,"<CONST_INT, %s>\n", yytext);
			fprintf(logout,"Line# %d: Token <CONST_INT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 575 "start.l"
{
					fprintf(tokenout,"<CONST_FLOAT, %s>\n", yytext);
					fprintf(logout,"Line# %d: Token <CONST_FLOAT> Lexeme %s found\n",line_count,yytext);
				}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 579 "start.l"
{
				fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR %c\n",line_count,yytext[0]); err_count++;
		}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 582 "start.l"
{
				fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR ",line_count); line_count++; err_count++;
				for(int i=0;i<yyleng;i++) 
				{
					if(yytext[i]==10 || yytext[i]==13) break;
					fprintf(logout, "%c",yytext[i]);
				}
				fprintf(logout, "\n");
				
		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 592 "start.l"
{	
			fprintf(logout,"Error at line# %d: EMPTY_CONST_CHAR %s\n",line_count,yytext); err_count++;
		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 595 "start.l"
{	
			fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR %s\n",line_count,yytext); err_count++;
		}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 598 "start.l"
{	
			fprintf(logout,"Error at line# %d: MULTICHAR_CONST_CHAR %s\n",line_count,yytext); err_count++;
		}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 601 "start.l"
{	
				fprintf(logout,"Error at line# %d:MULTICHAR_CONST_CHAR %s\n",line_count,yytext); err_count++;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 604 "start.l"
{	
				fprintf(logout,"Error at line# %d:MULTICHAR_CONST_CHAR %s\n",line_count,yytext); err_count++;
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 608 "start.l"
{	
									   string s=string(yytext); fprintf(tokenout,"<CONST_CHAR, ");
									   if(yyleng==4){
									   if(s[1] == '\\' && s[2]=='t') {fprintf(tokenout,"\t>\n");}
									   else if(s[1] == '\\' && s[2]=='r') {fprintf(tokenout,"\r>\n");}
									   else if(s[1] == '\\' && s[2]=='a') {fprintf(tokenout,"\a>\n");}  
								           else if(s[1] == '\\' && s[2]=='n') {fprintf(tokenout,"\n>\n");}
									   else if(s[1] == '\\' && s[2]=='b') {fprintf(tokenout,"\b>\n");}
								           else if(s[1] == '\\' && s[2]=='v') {fprintf(tokenout,"\v>\n");}
									   else if(s[1] == '\\' && s[2]=='f') {fprintf(tokenout,"\f>\n");}
									   else if(s[1] == '\\' && s[2]=='\'') {fprintf(tokenout,"\'>\n");}
									   else if(s[1] == '\\' && s[2]=='\"') {fprintf(tokenout,"\">\n");}
									   else if(s[1] == '\\' && s[2]=='\\') {fprintf(tokenout,"\\>\n");}}
								           else {fprintf(tokenout,"%c>\n",s[1]);}
									   fprintf(logout,"Line# %d: Token <CONST_CHAR> Lexeme ",line_count);
									   if(s[1] == '\\' && s[2]=='t') {fprintf(logout,"\t");}
									   else if(s[1] == '\\' && s[2]=='r') {fprintf(logout,"\r");}
									   else if(s[1] == '\\' && s[2]=='a') {fprintf(logout,"\a");}  
								           else if(s[1] == '\\' && s[2]=='n') {fprintf(logout,"\n");}
									   else if(s[1] == '\\' && s[2]=='b') {fprintf(logout,"\b");}
								           else if(s[1] == '\\' && s[2]=='v') {fprintf(logout,"\v");}
									   else if(s[1] == '\\' && s[2]=='f') {fprintf(logout,"\f");}
									   else {fprintf(logout,"%c",s[1]);}
								           fprintf(logout, " found\n");

									}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 634 "start.l"
{
				BEGIN STRINGSTART; 
			}
	YY_BREAK
case YY_STATE_EOF(STRINGSTART):
#line 637 "start.l"
{
					fprintf(logout,"Error at line# %d: UNFINISHED_COMMENT %s\n",line_count,yytext);	err_count++;BEGIN INITIAL;		
			      	   }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 640 "start.l"
{fprintf(logout,"Error at line# %d: UNFINISHED_STRING %s\n",line_count,yytext);err_count++;BEGIN INITIAL;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 641 "start.l"
{

			 	string s=(string)yytext; int sz=0;
				//cout<<yytext<<" "<<yyleng<<endl;
        		for(int i=0;i<yyleng-1;i++)
        		{	
				int aaa=yytext[i];
            			//if(yytext[i]=='\\' && yytext[i+1]=='n')
                			//sz++;
				if(aaa==10 || aaa==13)
                			sz++;
        		}
        		stack<char>stck; int i=yyleng-2;
			if(sz==0) {	fprintf(tokenout,"<SINGLE LINE STRING, ");
					fprintf(logout,"Line# %d: Token <SINGLE LINE STRING> Lexeme \"%s found\n",line_count,yytext);}
			else {fprintf(tokenout,"<MULTI LINE STRING, ");
					fprintf(logout,"Line# %d: Token <MULTI LINE STRING> Lexeme \"%s found\n",line_count,yytext);}
        		for( i=yyleng-2;i>0;i--)
       			 {	
				int aaa=(int)yytext[i];
				//cout<<aaa<<endl;
				if(yytext[i]==10 || yytext[i]==13) { if(aaa==10) line_count++; continue;}
				if(aaa==9){stck.push('\t');continue;}
            			if(yytext[i]=='t' && yytext[i-1]=='\\') {stck.push('\t');i--;}
            			else if(yytext[i]=='r' && yytext[i-1]=='\\') {stck.push('\r');i--;}
            			else if(yytext[i]=='a' && yytext[i-1]=='\\') {stck.push('\a');i--;}
           			 else if(yytext[i]=='b' && yytext[i-1]=='\\') {stck.push('\b');i--;}
            			else if(yytext[i]=='v' && yytext[i-1]=='\\') {stck.push('\v');i--;}
            			else if(yytext[i]=='f' && yytext[i-1]=='\\') {stck.push('\f');i--;}
            			else if(yytext[i]=='\'' && yytext[i-1]=='\\') {stck.push('\'');i--;}
				else if(yytext[i]=='\"' && yytext[i-1]=='\\') {stck.push('\"');i--;}
            			else if(yytext[i]=='\\') {}
            			else stck.push(yytext[i]);
       			 }
        		if(i==0) stck.push(yytext[i]);

        		while(stck.empty()==false)
        		{
            			char c=stck.top();
				int aaa=(int)c;
            			if(aaa==9) {fprintf(tokenout,"\t");stck.pop();continue;}
				fprintf(tokenout,"%c",c);
            			stck.pop();
        		}
       			fprintf(tokenout,">\n");
		         BEGIN INITIAL;
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 689 "start.l"
{ 	BEGIN MULTIPLECOMMENTSTART; fprintf(logout,"Line# %d: Token <MULTI LINE COMMENT> Lexeme %s",line_count,"\/\*");
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 691 "start.l"
{
								fprintf(logout,"%s found\n",yytext);
								BEGIN INITIAL;
							   }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 695 "start.l"
{
								fprintf(logout,"%s",yytext);
								BEGIN MULTIPLECOMMENTSTART;
				 		     }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 699 "start.l"
{
					fprintf(logout,"\n");line_count++;			
			      }
	YY_BREAK
case YY_STATE_EOF(MULTIPLECOMMENTSTART):
#line 702 "start.l"
{
					fprintf(logout,"Error at line# %d: UNFINISHED_COMMENT %s\n",line_count,yytext);	err_count++;BEGIN INITIAL;		
			      	   }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 706 "start.l"
{ 	fprintf(logout,"Line# %d: Token <SINGLE LINE COMMENT> Lexeme %s",line_count,yytext); BEGIN SINGLECOMMENTSTART;
	}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 708 "start.l"
{
					fprintf(logout,"%s",yytext);line_count++; BEGIN SINGLECOMMENTSTART;
				}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 711 "start.l"
{	
					for(int i=0;i<yyleng;i++){
					if(yytext[i]==10 || yytext[i]==13)break;
					fprintf(logout,"%c",yytext[i]);
					}
					
					fprintf(logout," found\n");line_count++; BEGIN INITIAL;
				}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 719 "start.l"
{
								fprintf(logout,"%s",yytext);
								BEGIN SINGLECOMMENTSTART;
				 		     }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 723 "start.l"
{
					fprintf(logout,"%s",yytext);BEGIN SINGLECOMMENTSTART2;
				}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 726 "start.l"
{
					fprintf(logout,"%s",yytext);BEGIN SINGLECOMMENTSTART;line_count++;
				}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 736 "start.l"
{
				fprintf(tokenout,"<ID, %s>\n", yytext);
				fprintf(logout,"Line# %d: Token <ID> Lexeme %s found\n",line_count,yytext); string s = (string)yytext;
				bool result = symbolTable.Insert((string)yytext,(string)yytext);
            			if(result)
            			{	
                			symbolTable.PrintAllScopeTable();
            			}
           			 else
          			  {	
					fprintf(logout,"\t%s already exists in the current ScopeTable\n",yytext);
                			
          			  }	
			  }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 750 "start.l"
{
					fprintf(logout,"Error at line# %d: TOO_MANY_DECIMAL_POINTS %s\n",line_count,yytext); err_count++;
				}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 753 "start.l"
{
							fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);err_count++;
						}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 756 "start.l"
{
							fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);err_count++;
						}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 759 "start.l"
{
							fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);err_count++;
						}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 762 "start.l"
{
							fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);err_count++;
						}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 765 "start.l"
{
				fprintf(logout,"Error at line# %d: INVALID_ID_SUFFIX_NUM_PREFIX %s\n",line_count,yytext);err_count++;
			}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 768 "start.l"
{
			fprintf(logout,"Error at line# %d: UNRECOGNIZED_CHAR %s\n",line_count,yytext);err_count++;
		}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 772 "start.l"
ECHO;
	YY_BREAK
#line 1989 "start.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLECOMMENTSTART):
case YY_STATE_EOF(SINGLECOMMENTSTART2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 207 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 207 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 206);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 772 "start.l"


int main(int argc, char** argv) {
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}

	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	symbolTable.EnterScope(10);
	logout= fopen("log.txt","w");
	tokenout= fopen("token.txt","w");

	yyin= fin;
	yylex();
	symbolTable.PrintCurrentScopeTable();
	fprintf(logout, "Total lines: %d\n", line_count);
	fprintf(logout, "Total errors: %d\n", err_count);
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}

